export default {
  ADD_CONTRACTED_PERSONS: 'ADD_CONTRACTED_PERSONS',
  ADD_CONTRACTED_PERSONS_SUCCESS: 'ADD_CONTRACTED_PERSONS_SUCCESS',
  ADD_CONTRACTED_PERSONS_FAILURE: 'ADD_CONTRACTED_PERSONS_FAILURE',
}
