export default {
    GET_QUARANTINE_TYPE: 'GET_QUARANTINE_TYPES',
    GET_QUARANTINE_TYPES_SUCCESS: 'GET_QUARANTINE_TYPES_SUCCESS',
    GET_QUARANTINE_TYPES_FAILURE: 'GET_QUARANTINE_TYPES_FAILURE',
};