export default {
  UPDATE_CONTRACTED_PERSONS: 'UPDATE_CONTRACTED_PERSONS',
  UPDATE_CONTRACTED_PERSONS_SUCCESS: 'UPDATE_CONTRACTED_PERSONS_SUCCESS',
  UPDATE_CONTRACTED_PERSONS_FAILURE: 'UPDATE_CONTRACTED_PERSONS_FAILURE',
}
