export default {
  UPDATE_ISOLATION_RECORD: 'UPDATE_ISOLATION_RECORD',
  UPDATE_ISOLATION_RECORD_SUCCESS: 'UPDATE_ISOLATION_RECORD_SUCCESS',
  UPDATE_ISOLATION_RECORD_FAILURE: 'UPDATE_ISOLATION_RECORD_FAILURE',
};
