export const apiUrls = {
  login: '/api/auth/login',
  logout: '/api/auth/logout',
  getZones: '/api/zones',
  getQuarantineTypes: '/api/quarantineTypes',
  resetPassword: '/api/auth/password',
  getPersonsByWard: '/api/dashboard/wards/',
  getPersonsDetails: '/api/persons',
  addContractedPersons: '/api/persons',
  locationsByType: '/api/form/locations/street_name',
  searchHospitalName: '/api/form/hospitals',
  updateContractedPersons: '/api/form/persons/:id',
  getDashboardEmbedUrl: '/api/dashboard/reports/gcc-dashboard',
  getPatientsLocation: '/api/dashboard/reports/map',
};
